const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
const root=__dirname;vm.runInThisContext(fs.readFileSync(path.join(root,'5goddesses-datenbank.js'),'utf8'));vm.runInThisContext(fs.readFileSync(path.join(root,'game-engine.js'),'utf8'));vm.runInThisContext(fs.readFileSync(path.join(root,'ai-player.js'),'utf8'));
const E=global.G5Engine,AI=global.G5AI,D=global.GODDESSES_DB.karten;let pass=0,fail=0;
function t(n,f){try{f();console.log('PASS',n);pass++}catch(e){console.error('FAIL',n,e.message);fail++;}}
function ok(x,m){if(!x)throw Error(m||'assert');}
function cardByName(n){return D.find(c=>c.name===n)}
function rt(c,owner=1,fd=false){return{bild:c.bild,owner,stufe:c.stufe||1,hearts:c.herzen??2,physicalShield:c.physischer_schild??0,astralShield:c.astraler_schild??0,physical:c.physische_staerke??0,astral:c.astrale_staerke??0,honor:c.ehre??0,ready:true,enteredTurn:0,attackedTurn:null,developedTurn:null,wonderTurn:null,wonderCostCurrent:Number(c.wunder?.kosten_ehre||0),effectUsesRemaining:c.effekt_zaehler_max??null,effectRoundsRemaining:c.effekt_dauer_kr??null,effectUsedTurn:null,effectState:{},faceDown:fd,developmentStack:[c.bild]}}
function P(i){return{index:i,name:i?'KI-Gegner':'Spieler',turnCount:1,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:null,discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[],recruitedThisTurn:false,drawDone:false}}
function S(){return{version:2,players:[P(0),P(1)],activePlayer:1,phaseIndex:4,roundSerial:4,sharedSecondary:null,azrLocks:[],log:[],pendingEquipment:null,pendingFieldCard:null,pendingWonderDraw:null,pendingRefugeStage2Choice:null,pendingBezEffect:null,pendingDamage:null,attack:null,winner:null,instinctWindowPassed:null,firstTurn:false}}
t('AI chooses and performs a legal development',()=>{const s=S(),dev=D.find(c=>c.name==='Die ungezähmte Flamme Saphira'&&c.deck_bereich==='entwicklung'),base=D.find(c=>c.bild===dev.grundkarte_bild);s.players[1].bezSlots[0]=rt(base,1);s.players[1].bezSlots[0].honor=2;s.players[1].development=[dev.bild];const choice=AI.chooseDevelopment(s);ok(choice&&choice.kind==='bez'&&choice.slot===0,'development not selected');const r=AI.step(s);ok(r.acted,'AI did not act');ok(s.players[1].bezSlots[0].bild===dev.bild,'development not performed');});
t('AI resolves its own wonder draw instead of stalling',()=>{const s=S(),draw=D.find(c=>c.deck_bereich==='astral');s.players[1].stacks.astral=[draw.bild];s.pendingWonderDraw={playerIndex:1,source:'refuge'};const r=AI.step(s);ok(r.acted,'pending wonder not handled');ok(!s.pendingWonderDraw,'pending wonder still open');ok(s.players[1].hand.includes(draw.bild),'card not drawn');});
t('AI uses an Instinkt card during a human rush and resolves its target',()=>{const s=S();s.activePlayer=0;s.phaseIndex=5;const ownBez=D.find(c=>c.hauptattribut==='BEZWINGERIN'&&c.deck_bereich==='bezwingerinnen');s.players[1].bezSlots[0]=rt(ownBez,1);const inst=cardByName('Aufopferung der S.H.I.E.L.D.');s.players[1].azr[0]=rt(inst,1,true);s.attack={attackerIndex:0,attackerSource:0,target:{type:'bez',slot:0},type:'physical'};let r=AI.defenseStep(s);ok(r.acted,'AI did not react');ok(s.pendingBezEffect?.sourcePlayer===1,'Instinkt target choice not opened');r=AI.defenseStep(s);ok(r.acted,'AI did not resolve target');ok(!s.pendingBezEffect,'Instinkt target still pending');ok(s.players[1].bezSlots[0].effectState.aufopferungPhysicalShield===1,'shield effect missing');});
t('battlefield delegates AI defense to the enhanced defenseStep',()=>{const ui=fs.readFileSync(path.join(root,'battlefield.js'),'utf8');ok(ui.includes('window.G5AI?.defenseStep?.(state)'),'defenseStep not wired');ok(ui.includes("window.G5_BATTLEFIELD_BUILD='1.95'"),'build not bumped');});
console.log(`RESULT ${pass} PASS / ${fail} FAIL`);if(fail)process.exit(1);
