const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','5goddesses-datenbank.js'),'utf8'));
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','game-engine.js'),'utf8'));
const E=global.G5Engine,DB=global.GODDESSES_DB.karten,card=n=>DB.find(c=>c.name===n);
const rt=(n,o=0,fd=false)=>{const c=card(n);return {bild:c.bild,owner:o,ownerIndex:o,controllerIndex:o,stufe:c.stufe||1,hearts:c.herzen??0,physicalShield:c.physischer_schild??0,astralShield:c.astraler_schild??0,physical:c.physische_staerke??0,astral:c.astrale_staerke??0,honor:c.ehre??0,ready:true,enteredTurn:0,attackedTurn:null,effectRoundsRemaining:c.effekt_dauer_kr??null,effectDisabled:false,effectState:{},faceDown:fd,developmentStack:[c.bild]};};
const P=i=>({index:i,name:'P'+(i+1),turnCount:1,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:null,discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[]});
const S=()=>({players:[P(0),P(1)],activePlayer:0,phaseIndex:4,sharedSecondary:null,log:[],attack:null,roundSerial:1,pendingBezEffect:null,pendingDamage:null});
let pass=0,fail=0;const ok=(x,m='assert')=>{if(!x)throw Error(m)},eq=(a,b,m='neq')=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(`${m}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`)},t=(n,f)=>{try{f();console.log('PASS',n);pass++}catch(e){console.error('FAIL',n,'-',e.message);fail++}};
function playExo(s){s.players[0].hand=[card('Exonova').bild];return E.playOpenAzr(s,0,0)}
t('Exonova database and Xalathir metadata captured',()=>{const x=card('Exonova'),ser=card('Die Weltenwanderin Serinith Solthar');ok(x.effekte[0].engine_key==='exonova_mass_astral');ok(x.effekt_symbol==='blitz');ok(!x.tags.includes('instinkt'));ok(ser.nebenattribute.includes('Astrean'));ok(ser.nebenattribute.includes('Xalathir'));ok(E.exonovaQualifier(rt('Die Weltenwanderin Serinith Solthar')))});
t('Exonova rejects unequal Bezwingerinnen counts without consuming hand card',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die Weltenwanderin Serinith Solthar',0);const r=playExo(s);ok(!r.ok,'unequal count allowed');ok(s.players[0].hand.length===1,'card consumed despite illegal play');ok(!s.players[0].azr[0])});
t('Mornak in Bez slot does not count as controlled Bezwingerin',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die Weltenwanderin Serinith Solthar',0);s.players[1].bezSlots[0]=rt('Mornak - Brut',1);eq(E.controlledBezwingerinnen(s,1).length,0);const r=playExo(s);ok(!r.ok,'Mornak incorrectly counted as Bezwingerin')});
t('Serinith satisfies Xalathir condition despite being Assassine',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die Weltenwanderin Serinith Solthar',0);s.players[1].bezSlots[0]=rt('Die Ewige Evelyn',1);const r=playExo(s);ok(r.ok,r.msg);ok(!s.players[0].azr[0],'Exonova not discarded');if(s.pendingDamage){const ch=E.currentShieldChoice(s);ok(ch,'shield choice expected');const src=ch.sources[0];const rr=E.chooseShieldSource(s,src.source,src.kind);ok(rr.ok,rr.msg)}eq(s.players[0].bezSlots[0].astralShield,0);eq(s.players[0].bezSlots[0].hearts,2);eq(s.players[1].bezSlots[0].hearts,1)});
t('Magierin or Unterstützerin satisfies condition; unrelated class does not',()=>{for(const name of ['Die Quelle der Reinheit Amelia','Wurzelpein Gebieterin Psilo Cybe']){const s=S();s.players[0].bezSlots[0]=rt(name,0);s.players[1].bezSlots[0]=rt('Die Ewige Evelyn',1);const c=card(name);if(['Magierin','Unterstützerin'].includes(c.klasse)){const r=playExo(s);ok(r.ok,`${name} rejected: ${r.msg}`)}} const s=S();s.players[0].bezSlots[0]=rt('Die Ewige Evelyn',0);s.players[1].bezSlots[0]=rt('Die ungezähmte Flamme Saphira',1);const r=playExo(s);ok(!r.ok,'unqualified class allowed')});
t('Exonova damages all Bezwingerinnen on both sides and respects ASTRAL shields',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die Weltenwanderin Serinith Solthar',0);s.players[0].bezSlots[1]=rt('Die ungezähmte Flamme Saphira',0);s.players[1].bezSlots[0]=rt('Die Ewige Evelyn',1);s.players[1].bezSlots[1]=rt('Die Quelle der Reinheit Amelia',1);s.players[0].bezSlots[0].astralShield=1;s.players[1].bezSlots[0].astralShield=1;const r=playExo(s);ok(r.ok,r.msg);ok(s.pendingDamage,'expected shield-choice damage queue');let guard=20;while(s.pendingDamage&&guard--){const ch=E.currentShieldChoice(s);if(!ch){throw Error('pending damage without choice');}const src=ch.sources[0];const rr=E.chooseShieldSource(s,src.source,src.kind);ok(rr.ok,rr.msg)}ok(guard>0,'damage loop');eq(s.players[0].bezSlots[0].astralShield,0);eq(s.players[1].bezSlots[0].astralShield,0);eq(s.players[0].bezSlots[1].hearts,1);eq(s.players[1].bezSlots[1].hearts,1)});
t('Exonova removes Bezwingerinnen reduced to 0 after mass damage',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die Weltenwanderin Serinith Solthar',0);s.players[1].bezSlots[0]=rt('Die Ewige Evelyn',1);s.players[0].bezSlots[0].astralShield=0;s.players[1].bezSlots[0].astralShield=0;s.players[0].bezSlots[0].hearts=1;s.players[1].bezSlots[0].hearts=1;const r=playExo(s);ok(r.ok,r.msg);ok(s.players[0].bezSlots[0]===null,'own 0-heart Bezwingerin survives');ok(s.players[1].bezSlots[0]===null,'enemy 0-heart Bezwingerin survives')});
console.log(`RESULT ${pass} PASS / ${fail} FAIL`);if(fail)process.exit(1);
