global.window=global;global.localStorage={getItem:()=>null,setItem(){},removeItem(){}};require('../5goddesses-datenbank.js');require('../game-engine.js');
const E=global.G5Engine,DB=global.GODDESSES_DB.karten;
const card=n=>DB.find(c=>c.name===n||c.name?.includes(n));
let pass=0,fail=0;function t(n,f){try{if(f()===false)throw Error('false');console.log('PASS',n);pass++;}catch(e){console.error('FAIL',n,'-',e.message);fail++;}}
function rt(n,owner=0,faceDown=false){const c=card(n);if(!c)throw Error('missing '+n);return {bild:c.bild,owner,stufe:Number(c.stufe||1),hearts:Number(c.herzen||0),physical:Number(c.physische_staerke||0),astral:Number(c.astrale_staerke||0),physicalShield:Number(c.physischer_schild||0),astralShield:Number(c.astraler_schild||0),honor:Number(c.ehre||0),ready:true,faceDown,effectState:{},developmentStack:[c.bild],wonderCostCurrent:Number(c.wunder?.kosten_ehre||0),enteredTurn:0,effectUsesRemaining:c.effekt_zaehler_max??null,effectUsedTurn:null,effectDisabled:false};}
function P(i){return {index:i,name:'P'+(i+1),turnCount:2,honorGrantedTurn:null,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:null,discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[],recruitedThisTurn:false,drawDone:false};}
function S(){return {version:2,players:[P(0),P(1)],activePlayer:0,startingPlayer:0,phaseIndex:4,sharedSecondary:null,voidZone:[],log:[],attack:null,roundSerial:5,pendingBezEffect:null,pendingDamage:null,pendingWonderDraw:null,pendingEquipment:null,pendingFieldCard:null,winner:null,firstTurn:false};}
function setupStrikelyn(enhanced=false){const s=S();s.players[0].bezSlots[0]=rt('Strikelyn',0);s.players[0].bezSlots[1]=rt('Die verschlingende Flut Calypso',0);let r=E.startStrikelynEffect(s,0,enhanced);if(!r.ok)throw Error(r.msg);r=E.resolveStrikelynTarget(s,'1');if(!r.ok)throw Error(r.msg);return s;}

t('Strikelyn starts with 2 charges',()=>{const s=S(),r=rt('Strikelyn');return r.effectUsesRemaining===2;});
t('normal Strikelyn costs 1 charge and stores protection',()=>{const s=setupStrikelyn(false),src=s.players[0].bezSlots[0],tar=s.players[0].bezSlots[1];return src.effectUsesRemaining===1&&tar.effectState.strikelynProtection?.enhanced===false;});
t('enhanced Strikelyn costs 2 charges',()=>{const s=setupStrikelyn(true),src=s.players[0].bezSlots[0],tar=s.players[0].bezSlots[1];return src.effectUsesRemaining===0&&tar.effectState.strikelynProtection?.enhanced===true;});
t('Strikelyn can only be used once per own combat round',()=>{const s=setupStrikelyn(false);return !E.startStrikelynEffect(s,0,false).ok;});
t('normal Strikelyn blocks enemy ASTRAL spell targeting',()=>{const s=setupStrikelyn(false);s.players[1].azr[0]=rt('ASTRAL-Feuerball',1,false);let r=E.startInstantAstralSpell(s,1,0);if(!r.ok)throw Error(r.msg);return !E.newAstralSpellTargets(s).some(x=>x.id==='1')&&!E.resolveNewAstralSpellTarget(s,'1').ok;});
t('normal Strikelyn blocks enemy Gegenstand targeting',()=>{const s=setupStrikelyn(false);s.players[1].azr[0]=rt('Lähmendes Nervengift',1,false);let r=E.startInstantRuestkammerItem(s,1,0);if(!r.ok)throw Error(r.msg);return !E.instantRuestkammerTargets(s).some(x=>x.id==='1')&&!E.resolveInstantRuestkammerTarget(s,'1').ok;});
t('normal Strikelyn does not block Gebote',()=>{const s=setupStrikelyn(false),target=s.players[0].bezSlots[1];return !E.targetProtectionReason(s,0,1,1,{deck_bereich:'astral',kartentyp:'ASTRAL-Gebot',fraktion:'Zwischenwelt'});});
t('enhanced Strikelyn blocks only Zwischenwelt Gebote',()=>{const s=setupStrikelyn(true);const z=E.targetProtectionReason(s,0,1,1,{deck_bereich:'astral',kartentyp:'ASTRAL-Gebot',fraktion:'Zwischenwelt'});const a=E.targetProtectionReason(s,0,1,1,{deck_bereich:'astral',kartentyp:'ASTRAL-Gebot',fraktion:'Astralwelt'});return !!z&&!a;});
t('Strikelyn protection expires at next own supply-start',()=>{const s=setupStrikelyn(false);s.phaseIndex=2;E.advancePhase(s);return !s.players[0].bezSlots[1].effectState.strikelynProtection;});
t('Dunkelglanz blocks enemy ASTRAL spell and Gegenstand',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die verschlingende Flut Calypso',0);s.players[0].equipment[0].armor=rt('Mantel der Stille Dunkelglanz',0);const sp=E.targetProtectionReason(s,0,0,1,card('ASTRAL-Feuerball'));const it=E.targetProtectionReason(s,0,0,1,card('Lähmendes Nervengift'));return !!sp&&!!it;});
t('Dunkelglanz does not block Gebote',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die verschlingende Flut Calypso',0);s.players[0].equipment[0].armor=rt('Mantel der Stille Dunkelglanz',0);return !E.targetProtectionReason(s,0,0,1,{deck_bereich:'astral',kartentyp:'ASTRAL-Gebot',fraktion:'Zwischenwelt'});});
t('Dunkelglanz protection ends immediately when armor leaves',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die verschlingende Flut Calypso',0);s.players[0].equipment[0].armor=rt('Mantel der Stille Dunkelglanz',0);s.players[0].equipment[0].armor=null;return !E.targetProtectionReason(s,0,0,1,card('ASTRAL-Feuerball'));});
t('AoE Exonova is not blocked because it does not choose protected Bez as target',()=>{const s=setupStrikelyn(true);return !E.targetProtectionReason(s,0,1,1,card('Exonova'))||card('Exonova').kartentyp==='ASTRAL-Gebot';});
t('Exekution with no valid legal target is discarded without effect',()=>{const s=S();let b=rt('Die verschlingende Flut Calypso',1);b.hearts=2;s.players[1].bezSlots[0]=b;s.players[0].azr[0]=rt('Exekution',0,false);const r=E.startInstantAstralSpell(s,0,0);return r.ok&&!s.pendingBezEffect&&!s.players[0].azr[0]&&s.players[0].discard.includes(card('Exekution').bild);});
console.log(`RESULT ${pass} PASS / ${fail} FAIL`);process.exitCode=fail?1:0;
