const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','5goddesses-datenbank.js'),'utf8'));
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','game-engine.js'),'utf8'));
const E=global.G5Engine,DB=global.GODDESSES_DB.karten,card=n=>DB.find(c=>c.name===n);
const rt=(n,o=0,fd=false)=>{const c=card(n);return {bild:c.bild,owner:o,ownerIndex:o,controllerIndex:o,stufe:c.stufe||1,hearts:c.herzen??0,physicalShield:c.physischer_schild??0,astralShield:c.astraler_schild??0,physical:c.physische_staerke??0,astral:c.astrale_staerke??0,honor:c.ehre??0,ready:true,enteredTurn:0,attackedTurn:null,effectRoundsRemaining:c.effekt_dauer_kr??null,effectDisabled:false,effectState:{testMarker:'preserve'},faceDown:fd,developmentStack:[c.bild]};};
const P=i=>({index:i,name:'P'+(i+1),turnCount:1,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:null,discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[]});
const S=()=>({players:[P(0),P(1)],activePlayer:0,phaseIndex:4,sharedSecondary:null,log:[],attack:null,roundSerial:1,pendingBezEffect:null,pendingDamage:null});
let pass=0,fail=0;const ok=(x,m='assert')=>{if(!x)throw Error(m)},eq=(a,b,m='neq')=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(`${m}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`)},t=(n,f)=>{try{f();console.log('PASS',n);pass++}catch(e){console.error('FAIL',n,'-',e.message);fail++}};
function playReset(s){s.players[0].hand=[card('System Reset').bild];return E.playOpenAzr(s,0,0)}
t('System Reset database metadata',()=>{const c=card('System Reset');ok(c.effekte.some(e=>e.engine_key==='system_reset_return_azr'));eq(c.effekt_symbol,'blitz');ok(!(c.tags||[]).includes('instinkt'));});
t('Cannot play System Reset without opponent AZR target and card remains in hand',()=>{const s=S(),r=playReset(s);ok(!r.ok,'illegal play allowed');eq(s.players[0].hand,[card('System Reset').bild]);ok(!s.players[0].azr[0]);});
t('Targets only occupied opponent AZR slots',()=>{const s=S();s.players[0].azr[2]=rt('Nebel',0,false);s.players[1].azr[1]=rt('Überwachungssektor',1,false);const r=playReset(s);ok(r.ok&&r.pending,r.msg);const ts=E.newAstralSpellTargets(s);eq(ts.length,1);eq(ts[0].id,'1');});
t('Returns a face-up opponent AZR card to its owners hand and discards System Reset',()=>{const s=S(),target=rt('Überwachungssektor',1,false);s.players[1].azr[2]=target;const r=playReset(s);ok(r.ok&&r.pending,r.msg);const rr=E.resolveNewAstralSpellTarget(s,'2');ok(rr.ok,rr.msg);ok(!s.players[1].azr[2]);ok(s.players[1].hand.includes(target.bild));ok(!s.players[0].azr[0]);ok(s.players[0].discard.includes(card('System Reset').bild));});
t('Returns a face-down set card without activating or discarding it',()=>{const s=S(),target=rt('Nebel',1,true);target.effectState={testMarker:'preserve'};s.players[1].azr[0]=target;const discardBefore=s.players[1].discard.length;const r=playReset(s);ok(r.ok&&r.pending,r.msg);const rr=E.resolveNewAstralSpellTarget(s,'0');ok(rr.ok,rr.msg);ok(!s.players[1].azr[0]);ok(s.players[1].hand.includes(target.bild));eq(s.players[1].discard.length,discardBefore);ok(!s.pendingBezEffect);});
t('Returns card to actual owner even when it is in opponents AZR',()=>{const s=S(),target=rt('Mornak - Brut',0,true);s.players[1].azr[1]=target;const r=playReset(s);ok(r.ok&&r.pending,r.msg);const beforeOwn=s.players[0].hand.length,beforeOpp=s.players[1].hand.length;const rr=E.resolveNewAstralSpellTarget(s,'1');ok(rr.ok,rr.msg);eq(s.players[0].hand.length,beforeOwn+1);eq(s.players[1].hand.length,beforeOpp);ok(s.players[0].hand.includes(target.bild));});
t('Invalidated target is not resolved and System Reset remains pending',()=>{const s=S();s.players[1].azr[0]=rt('Nebel',1,true);const r=playReset(s);ok(r.ok&&r.pending);s.players[1].azr[0]=null;const rr=E.resolveNewAstralSpellTarget(s,'0');ok(!rr.ok);ok(s.pendingBezEffect?.type==='system_reset_target');ok(s.players[0].azr[0]);});
console.log(`RESULT ${pass} PASS / ${fail} FAIL`);if(fail)process.exit(1);
