const fs=require('fs'),vm=require('vm'),path=require('path');
global.window=global;global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','5goddesses-datenbank.js'),'utf8'));
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..','game-engine.js'),'utf8'));
const E=global.G5Engine,DB=global.GODDESSES_DB.karten,card=n=>DB.find(c=>c.name===n);
const rt=(n,o=0,fd=false)=>{const c=card(n);if(!c)throw Error('missing '+n);return {bild:c.bild,owner:o,stufe:c.stufe||1,hearts:c.herzen??0,physicalShield:c.physischer_schild??0,astralShield:c.astraler_schild??0,physical:c.physische_staerke??0,astral:c.astrale_staerke??0,honor:c.ehre??0,ready:true,enteredTurn:0,attackedTurn:null,developedTurn:null,wonderTurn:null,wonderCostCurrent:Number(c.wunder?.kosten_ehre??0),effectRoundsRemaining:c.effekt_dauer_kr??null,effectDisabled:false,effectState:{},faceDown:fd,developmentStack:[c.bild]};};
const P=i=>({index:i,name:'P'+(i+1),turnCount:1,honorGrantedTurn:null,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:null,discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[],recruitedThisTurn:false,drawDone:false});
const S=(phase=4)=>({version:2,players:[P(0),P(1)],activePlayer:0,startingPlayer:0,phaseIndex:phase,sharedSecondary:null,voidZone:[],log:[],attack:null,roundSerial:5,pendingBezEffect:null,pendingDamage:null,pendingEquipment:null,pendingFieldCard:null,pendingWonderDraw:null,pendingRefugeStage2Choice:null,winner:null,firstTurn:false});
let pass=0,fail=0;const ok=(x,m='assert')=>{if(!x)throw Error(m)},eq=(a,b,m='neq')=>{if(JSON.stringify(a)!==JSON.stringify(b))throw Error(`${m}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`)},t=(n,f)=>{try{f();console.log('PASS',n);pass++}catch(e){console.error('FAIL',n,'-',e.stack||e.message);fail++}};
function play(s,name,player=0,slot=0){s.players[player].hand=[card(name).bild];return E.playOpenAzr(s,player,slot);}

t('Portalgeschoss is explicitly Instinkt and offered in opponent rush reaction window',()=>{const c=card('Portalgeschoss');ok(c.tags.includes('instinkt'));ok(c.effekte.some(e=>e.instinkt===true));const s=S(5);s.activePlayer=1;s.players[0].bezSlots[0]=rt('Die Ewige Evelyn',0);s.players[1].bezSlots[0]=rt('Die Säule des Lebens Talisia',1);s.attack={attackerKind:'bez',attackerSlot:0,target:{type:'bez',slot:0},attackType:'physical'};s.players[0].azr[0]=rt('Portalgeschoss',0,true);const cs=E.instinctCandidates(s);ok(cs.some(x=>x.name==='Portalgeschoss'));});

t('Tauschportal metadata uses armor helmet shield, never weapon',()=>{const c=card('Tauschportal');const e=c.effekte.find(x=>x.engine_key==='tauschportal_swap_equipment');eq(e.allowed_equipment,['Rüstung','Kopfschutz','Schild']);ok(!e.allowed_equipment.includes('Waffe'));});

t('Tauschportal cannot be played with only weapon equipment',()=>{const s=S();s.players[1].bezSlots=[rt('Die Ewige Evelyn',1),rt('Die Säule des Lebens Talisia',1)];s.players[1].equipment[0].weapon=rt('Instabiler Stab',1);const r=play(s,'Tauschportal');ok(!r.ok,'weapon incorrectly accepted');ok(s.players[0].hand.includes(card('Tauschportal').bild));});

t('Tauschportal moves armor to empty same-type slot',()=>{const s=S();s.players[1].bezSlots=[rt('Die Ewige Evelyn',1),rt('Die Säule des Lebens Talisia',1)];const armor=rt('Legionsbrustpanzer',1);s.players[1].equipment[0].armor=armor;let r=play(s,'Tauschportal');ok(r.ok&&r.pending,r.msg);let ts=E.newAstralSpellTargets(s);ok(ts.some(x=>x.id==='0:armor'));r=E.resolveNewAstralSpellTarget(s,'0:armor');ok(r.ok&&r.pending,r.msg);r=E.resolveNewAstralSpellTarget(s,'1');ok(r.ok,r.msg);ok(!s.players[1].equipment[0].armor);eq(s.players[1].equipment[1].armor.bild,armor.bild);ok(s.players[0].discard.includes(card('Tauschportal').bild));});

t('Tauschportal swaps occupied shield slots without re-playing cards',()=>{const s=S();s.players[1].bezSlots=[rt('Die Ewige Evelyn',1),rt('Die Säule des Lebens Talisia',1)];const a=rt('Legionsschild',1),b=rt('Energieschild',1);a.effectState.marker='A';b.effectState.marker='B';s.players[1].equipment[0].shield=a;s.players[1].equipment[1].shield=b;let r=play(s,'Tauschportal');ok(r.ok);r=E.resolveNewAstralSpellTarget(s,'0:shield');ok(r.ok);r=E.resolveNewAstralSpellTarget(s,'1');ok(r.ok);eq(s.players[1].equipment[0].shield.effectState.marker,'B');eq(s.players[1].equipment[1].shield.effectState.marker,'A');});

t('Zeitlose Unterwerfung reduces ordinary wonder by 1 for non-Astralwelt',()=>{const s=S();const b=rt('Die Säule des Lebens Talisia',0);s.players[0].bezSlots[0]=b;let r=play(s,'Zeitlose Unterwerfung');ok(r.ok&&r.pending,r.msg);r=E.resolveNewAstralSpellTarget(s,'0');ok(r.ok,r.msg);eq(b.wonderCostCurrent,1);eq(b.effectState.zeitloseUnterwerfung.appliedReduction,1);});

t('Zeitlose Unterwerfung reduces Astralwelt wonder by 2 and never below zero',()=>{const s=S();const b=rt('Die Ewige Evelyn',0);s.players[0].bezSlots[0]=b;let r=play(s,'Zeitlose Unterwerfung');ok(r.ok);r=E.resolveNewAstralSpellTarget(s,'0');ok(r.ok);eq(b.wonderCostCurrent,0);eq(b.effectState.zeitloseUnterwerfung.appliedReduction,2);});

t('Zeitlose Unterwerfung expires at end of current KR and restores dynamic wonder cost',()=>{const s=S(4);const b=rt('Die Ewige Evelyn',0);s.players[0].bezSlots[0]=b;let r=play(s,'Zeitlose Unterwerfung');ok(r.ok);E.resolveNewAstralSpellTarget(s,'0');eq(b.wonderCostCurrent,0);b.wonderCostCurrent+=1; // simulate a card effect that permanently raises future wonder cost this round
s.phaseIndex=8;r=E.advancePhase(s);ok(r.ok,r.msg);eq(b.wonderCostCurrent,3,'must restore only applied 2 on top of dynamic +1');ok(!b.effectState.zeitloseUnterwerfung);});


t('Zeitlose Unterwerfung also reduces a specialized targeted wonder (Talisia)',()=>{const s=S();const tal=rt('Die Säule des Lebens Talisia',0);tal.honor=1;tal.astralShield=1;s.players[0].bezSlots[0]=tal;s.players[0].bezSlots[1]=rt('Die Ewige Evelyn',0);let r=play(s,'Zeitlose Unterwerfung');ok(r.ok);E.resolveNewAstralSpellTarget(s,'0');eq(tal.wonderCostCurrent,1);r=E.startTalisia1Wonder(s,0);ok(r.ok&&r.pending,r.msg);r=E.resolveCheckedEffectTarget(s,'bez:0');ok(r.ok&&r.pending,r.msg);r=E.resolveCheckedEffectTarget(s,'1');ok(r.ok,r.msg);eq(tal.honor,0,'discounted Talisia wonder should cost exactly 1');});

t('Strahl des Vergessens metadata defines Instinkt and Leere',()=>{const c=card('Strahl des Vergessens');ok(c.tags.includes('instinkt'));ok(c.tags.includes('leere'));ok(c.effekte.some(e=>e.engine_key==='strahl_des_vergessens_void'&&e.instinkt===true));});

t('Strahl des Vergessens removes any chosen Bezwingerin and attached equipment from play while preserving state',()=>{const s=S();const b=rt('Die Ewige Evelyn',1);b.hearts=1;b.honor=4;b.ready=false;b.effectState.special='keep';b.developmentStack.push('dummy-stage2');s.players[1].bezSlots[1]=b;const armor=rt('Legionsbrustpanzer',1);armor.effectState.eq='keep';s.players[1].equipment[1].armor=armor;let r=play(s,'Strahl des Vergessens');ok(r.ok&&r.pending,r.msg);const choices=E.newAstralSpellTargets(s);ok(choices.some(x=>x.id==='1:1'));r=E.resolveNewAstralSpellTarget(s,'1:1');ok(r.ok,r.msg);ok(!s.players[1].bezSlots[1]);ok(!s.players[1].equipment[1].armor);eq(s.voidZone.length,1);const v=s.voidZone[0];eq(v.runtime.hearts,1);eq(v.runtime.honor,4);eq(v.runtime.ready,false);eq(v.runtime.effectState.special,'keep');eq(v.runtime.developmentStack.length,2);eq(v.equipment.armor.effectState.eq,'keep');});

t('Strahl des Vergessens cancels a prepared combat if attacker or target leaves play',()=>{const s=S(5);s.players[0].bezSlots[0]=rt('Die Ewige Evelyn',0);s.players[1].bezSlots[0]=rt('Die Säule des Lebens Talisia',1);s.attack={attackerKind:'bez',attackerSlot:0,target:{type:'bez',slot:0},attackType:'physical'};s.players[1].azr[0]=rt('Strahl des Vergessens',1,false);const r=E.startInstantAstralSpell(s,1,0);ok(r.ok&&r.pending,r.msg);const rr=E.resolveNewAstralSpellTarget(s,'0:0');ok(rr.ok,rr.msg);ok(!s.attack,'attack not cancelled');});

t('Leere returns card with equipment to exact original slot at casters next reached VP/NP',()=>{const s=S(4);const b=rt('Die Ewige Evelyn',1);b.hearts=1;s.players[1].bezSlots[0]=b;const helm=rt('Hut der Weisheit',1);s.players[1].equipment[0].helmet=helm;let r=play(s,'Strahl des Vergessens',0,0);ok(r.ok);E.resolveNewAstralSpellTarget(s,'1:0');eq(s.voidZone.length,1);s.phaseIndex=6; // combat -> advance directly to resupply, which is caster P0's next qualifying phase
r=E.advancePhase(s);ok(r.ok,r.msg);eq(s.players[1].bezSlots[0].bild,b.bild);eq(s.players[1].bezSlots[0].hearts,1);eq(s.players[1].equipment[0].helmet.bild,helm.bild);eq(s.voidZone.length,0);});

t('Occupied original field causes permanent Leere with no alternative-slot return',()=>{const s=S(4);s.players[1].bezSlots[0]=rt('Die Ewige Evelyn',1);let r=play(s,'Strahl des Vergessens');ok(r.ok);E.resolveNewAstralSpellTarget(s,'1:0');s.players[1].bezSlots[0]=rt('Die Säule des Lebens Talisia',1);ok(!s.players[1].bezSlots[1]);s.phaseIndex=6;r=E.advancePhase(s);ok(r.ok);eq(card(E.cardData(s.players[1].bezSlots[0])?.name)?.name,'Die Säule des Lebens Talisia');eq(s.voidZone.length,1);ok(s.voidZone[0].permanent);ok(!s.players[1].bezSlots[1],'must not use alternative slot');});

t('Strahl des Vergessens is offered as Instinkt during opponent supported phases',()=>{const s=S(5);s.activePlayer=1;s.players[0].azr[0]=rt('Strahl des Vergessens',0,true);s.players[1].bezSlots[0]=rt('Die Säule des Lebens Talisia',1);ok(E.instinctCandidates(s).some(x=>x.name==='Strahl des Vergessens'));});

console.log(`RESULT ${pass} PASS / ${fail} FAIL`);if(fail)process.exit(1);
