const fs=require('fs'),vm=require('vm');
global.window=global;
global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
vm.runInThisContext(fs.readFileSync(require('path').join(__dirname,'..','5goddesses-datenbank.js'),'utf8'),{filename:'5goddesses-datenbank.js'});
vm.runInThisContext(fs.readFileSync(require('path').join(__dirname,'..','game-engine.js'),'utf8'),{filename:'game-engine.js'});
const E=global.G5Engine, DB=global.GODDESSES_DB.karten;
const card=n=>DB.find(c=>c.name===n);
const rt=(n,owner=0,faceDown=false)=>{const c=card(n);return {bild:c.bild,owner,controllerIndex:owner,ownerIndex:owner,stufe:c.stufe||1,hearts:c.herzen??0,physicalShield:c.physischer_schild??0,astralShield:c.astraler_schild??0,physical:c.physische_staerke??0,astral:c.astrale_staerke??0,honor:c.ehre??0,ready:false,enteredTurn:0,attackedTurn:null,developedTurn:null,wonderTurn:null,wonderCostCurrent:Number(c.wunder?.kosten_ehre??0),berserkerMarks:0,effectUsedTurn:null,effectUsesRemaining:c.effekt_zaehler_max??null,effectRoundsRemaining:c.effekt_dauer_kr??null,effectDisabled:false,effectState:{},faceDown,developmentStack:[c.bild]};};
const emptyP=i=>({index:i,name:`P${i+1}`,turnCount:1,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,discard:[],recruitedThisTurn:false,drawDone:false,stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[]});
const state=()=>({players:[emptyP(0),emptyP(1)],activePlayer:0,phaseIndex:4,sharedSecondary:null,log:[],pendingBezEffect:null,pendingFieldCard:null,pendingDamage:null,attack:null});
let pass=0,fail=0;function t(name,fn){try{fn();console.log('PASS',name);pass++;}catch(e){console.error('FAIL',name,'-',e.message);fail++;}}function ok(x,m='assertion failed'){if(!x)throw new Error(m)}function eq(a,b,m='not equal'){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(`${m}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`)}

t('Mornak database text and alternate areas corrected',()=>{const c=card('Mornak - Brut');eq(c.effekte[0].alternate_areas,['secondary','bez']);ok(c.effekt_text.includes('freien Bezwingerinnen-Bereich'));ok(!c.effekt_text.includes('freien ASTRAL'))});
t('Mornak can be played from hand into free Bez slot without consuming recruitment',()=>{const s=state();s.players[0].hand=[card('Mornak - Brut').bild];let r=E.playFieldFromHand(s,0,'bez:1');ok(r.ok,r.msg);ok(E.cardData(s.players[0].bezSlots[1]).name==='Mornak - Brut');ok(!s.players[0].recruitedThisTurn);ok(s.players[0].bezSlots[1].ready===false)});
t('Mornak cannot be played openly into own AZR',()=>{const s=state();s.players[0].hand=[card('Mornak - Brut').bild];let r=E.playOpenAzr(s,0,0);ok(!r.ok,'open AZR unexpectedly allowed');ok(s.players[0].hand.length===1)});
t('Mornak token targets include primary, secondary and free Bez slots but no own AZR',()=>{const s=state();const ids=E.mornakTokenTargets(s,0,false).map(x=>x.id);eq(ids,['primary','secondary','bez:0','bez:1']);s.pendingBezEffect={type:'mornak_token_place',sourcePlayer:0,allowEnemyAzr:false,source:'Test'};let r=E.resolveMornakTokenPlacement(s,'bez:0');ok(r.ok,r.msg);ok(s.players[0].bezSlots[0].ready===false,'Mornak token must have deployment delay')});
t('Mornak revealed from AZR can move to Bez slot and leaves AZR',()=>{const s=state();s.players[0].azr[0]=rt('Mornak - Brut',0,false);s.pendingFieldCard={owner:0,azrSlot:0,area:'mornak_choice'};let r=E.moveMornakFromAzr(s,0,'bez:0');ok(r.ok,r.msg);ok(!s.players[0].azr[0]);ok(E.cardData(s.players[0].bezSlots[0]).name==='Mornak - Brut')});
t('Equipment cannot be attached to Mornak occupying Bez slot',()=>{const s=state();s.players[0].bezSlots[0]=rt('Mornak - Brut');const eqCard=DB.find(c=>c.deck_bereich==='ruestkammer'&&['Waffe','Schild','Rüstung','Kopfschutz'].includes(c.kartentyp));ok(eqCard,'no equipment card');s.players[0].hand=[eqCard.bild];const kind=E.equipmentKind(eqCard);let r=E.equipFromHand(s,0,0,kind);ok(!r.ok,'equipment unexpectedly attached');ok(s.players[0].hand.length===1)});
t('Mornak in Bez slot is offered as Nemesis damage redirect and dies after taking its 1 heart',()=>{const s=state();s.players[0].bezSlots[0]=rt('Geißel der Galaxie Nemesis');s.players[0].bezSlots[1]=rt('Mornak - Brut');s.players[0].bezSlots[0].hearts=5;s.players[0].bezSlots[0].physicalShield=0;s.players[0].bezSlots[1].hearts=1;s.pendingDamage={packets:[{playerIndex:0,bezSlot:0,type:'physical',remaining:2,shieldLoss:0,heartLoss:0}],packetIndex:0};let ch=E.currentShieldChoice(s);ok(ch&&ch.sources.some(x=>x.source==='mornak'),'Mornak redirect missing');let src=ch.sources.find(x=>x.source==='mornak');let r=E.chooseShieldSource(s,'mornak',src.kind);ok(r.ok,r.msg);ok(s.players[0].bezSlots[1]===null,'destroyed Mornak still occupies Bez slot');eq(s.players[0].bezSlots[0].hearts,4,'overflow did not hit Nemesis')});
t('Überwachungssektor database effect is permanent and rule-facedown preserving',()=>{const c=card('Überwachungssektor');ok(c.effekt_symbol==='permanent');ok(c.effekte[0].engine_key==='ueberwachungssektor');ok(c.effekte[0].rules_still_face_down===true);ok(c.effekte[0].applies_to_future_set_cards===true)});
t('Überwachungssektor reveals only opposing player AZR while active',()=>{const s=state();s.sharedSecondary=rt('Überwachungssektor',0,false);ok(E.surveillanceRevealsAzr(s,1));ok(!E.surveillanceRevealsAzr(s,0));s.sharedSecondary.effectDisabled=true;ok(!E.surveillanceRevealsAzr(s,1));s.sharedSecondary.effectDisabled=false;s.sharedSecondary.faceDown=true;ok(!E.surveillanceRevealsAzr(s,1))});
t('Cards set after Überwachungssektor remain rule-faceDown while visibility condition applies',()=>{const s=state();s.sharedSecondary=rt('Überwachungssektor',0,false);s.activePlayer=1;s.players[1].hand=[DB.find(c=>c.deck_bereich==='astral'&&c.name!=='Überwachungssektor').bild];let r=E.setFaceDown(s,0,0);ok(r.ok,r.msg);ok(s.players[1].azr[0].faceDown===true,'rule state was incorrectly flipped');ok(E.surveillanceRevealsAzr(s,1),'visibility not active for newly set card')});
console.log(`RESULT ${pass} PASS / ${fail} FAIL`);if(fail)process.exit(1);
