global.window=global;global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};require('../5goddesses-datenbank.js');require('../game-engine.js');
const E=global.G5Engine, DB=global.GODDESSES_DB.karten, card=n=>DB.find(c=>c.name===n);
let pass=0,fail=0; function t(n,f){try{if(f()===false)throw Error('false');console.log('PASS',n);pass++}catch(e){console.error('FAIL',n,e.stack||e);fail++}}
function rt(n,o=0,fd=false,ready=true){const c=card(n);if(!c)throw Error('missing '+n);return {bild:c.bild,owner:o,controllerIndex:o,ownerIndex:o,stufe:c.stufe||1,hearts:c.herzen??0,physicalShield:c.physischer_schild??0,astralShield:c.astraler_schild??0,physical:c.physische_staerke??0,astral:c.astrale_staerke??0,honor:c.ehre??0,ready,enteredTurn:0,attackedTurn:null,developedTurn:null,wonderTurn:null,wonderCostCurrent:Number(c.wunder?.kosten_ehre??0),berserkerMarks:0,effectUsedTurn:null,effectUsesRemaining:c.effekt_zaehler_max??null,effectRoundsRemaining:c.effekt_dauer_kr??null,effectDisabled:false,effectState:{},faceDown:fd,developmentStack:[c.bild]};}
const P=i=>({index:i,name:'P'+i,turnCount:2,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:rt('Zauberkessel Sternenwacht',i,false,true),discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[],recruitedThisTurn:false,drawDone:false});
const S=(phaseIndex=4)=>({version:2,players:[P(0),P(1)],activePlayer:0,startingPlayer:0,phaseIndex,sharedSecondary:null,voidZone:[],log:[],roundSerial:8,pendingBezEffect:null,pendingEquipment:null,pendingFieldCard:null,pendingDamage:null,pendingWonderDraw:null,pendingRefugeStage2Choice:null,winner:null,firstTurn:false,attack:null,instinctWindowPassed:null,azrLocks:[]});
const ruest=DB.filter(c=>c.deck_bereich==='ruestkammer');
// 50 Karten: Daten-/Runtime-Audit pro Karte.
for(const c of ruest){t(`Rüstkammer-Karte vollständig registriert: ${c.name}`,()=>c.kartengruppe==='Rüstkammer'&&c.hauptattribut==='RÜSTKAMMER'&&c.stufe===1&&!!c.id&&!!c.bild&&Array.isArray(c.effekte)&&c.effekte.length>0);}

// 11 verhaltensbasierte Regressionen für die wichtigsten generischen/Sondermechaniken.
t('Legionsschild: permanenter physischer Ausrüstungsschild + Blitz-Ehre',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[0].hand=[card('Legionsschild').bild];const before=s.players[0].bezSlots[0].honor;const r=E.equipFromHand(s,0,0,'shield');const sh=s.players[0].equipment[0].shield;return r.ok&&sh&&sh.physicalShield===1&&s.players[0].bezSlots[0].honor===before+1;});
t('Ubusa Brustpanzer: je 1 physischer und ASTRAL-Ausrüstungsschild',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[0].hand=[card('Ubusa Brustpanzer').bild];const r=E.equipFromHand(s,0,0,'armor'),a=s.players[0].equipment[0].armor;return r.ok&&a.physicalShield===1&&a.astralShield===1;});
t('Hut der Weisheit: +1 Ehre beim Anlegen',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[0].hand=[card('Hut der Weisheit').bild];const r=E.equipFromHand(s,0,0,'helmet');return r.ok&&s.players[0].bezSlots[0].honor===1;});
t('Fragmentfresser Schlund: findet ausschließlich ASTRALFRAGMENT in eigener Ablage',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[0].discard=[card('Astralfragment der Ehre').bild,card('Legionshelm').bild];s.players[0].hand=[card('Fragmentfresser Schlund').bild];const r=E.equipFromHand(s,0,0,'weapon');if(!r.ok)return false;const ts=E.fragmentfresserSchlundTargets(s,0);if(ts.length!==1||!String(ts[0].name).includes('Astralfragment'))return false;const z=E.resolveFragmentfresserSchlund(s,ts[0].id);return z.ok&&s.players[0].hand.includes(card('Astralfragment der Ehre').bild)&&!s.players[0].discard.includes(card('Astralfragment der Ehre').bild);});
t('Lebensfresserschild Hunger: setzt Herzen auf 1, +3 Basisschild und startet Dauer 2',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[0].bezSlots[0].hearts=3;s.players[0].hand=[card('Lebensfresserschild Hunger').bild];const r=E.equipFromHand(s,0,0,'shield'),sh=s.players[0].equipment[0].shield,b=s.players[0].bezSlots[0];return r.ok&&b.hearts===1&&b.physicalShield===3&&sh.effectRoundsRemaining===2;});
t('Parierdolch: speichert und aktiviert genau eine Gegenangriff-Ausweichnutzung',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[0].hand=[card('Parierdolch').bild];let r=E.equipFromHand(s,0,0,'weapon');if(!r.ok)return false;const w=s.players[0].equipment[0].weapon;if(w.effectState.counterDodgeUses!==1)return false;r=E.activateParierdolchDodge(s,0);return r.ok&&w.effectState.counterDodgeActive===true;});
t('Die Bastion bringt Dir Erleuchtung: +1 Zuflucht-Ehre und Ablage',()=>{const s=S();s.players[0].azr[0]=rt('Die Bastion bringt Dir Erleuchtung',0,false,true);const before=s.players[0].refuge.honor;const r=E.startInstantRuestkammerItem(s,0,0);return r.ok&&s.players[0].refuge.honor===before+1&&!s.players[0].azr[0]&&s.players[0].discard.includes(card('Die Bastion bringt Dir Erleuchtung').bild);});
t('Lähmendes Nervengift: gegnerisches Ziel erhält Sekundärangriff bis Rundenende',()=>{const s=S();s.players[1].bezSlots[1]=rt('Die ungezähmte Flamme Saphira',1);s.players[0].azr[0]=rt('Lähmendes Nervengift');let r=E.startInstantRuestkammerItem(s,0,0);if(!r.ok)return false;const ts=E.instantRuestkammerTargets(s);if(!ts.some(x=>String(x.id)==='1'))return false;r=E.resolveInstantRuestkammerTarget(s,'1');return r.ok&&E.hasSecondaryAttack(s.players[1].bezSlots[1],s);});
t('Trank der Stärke: eigene Bezwingerin erhält +1 physisch für genau einen Kampf',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[0].azr[0]=rt('Trank der Stärke');let r=E.startInstantRuestkammerItem(s,0,0);if(!r.ok)return false;r=E.resolveInstantRuestkammerTarget(s,'0');return r.ok&&Number(s.players[0].bezSlots[0].effectState?.trankStaerkePhysicalBonus||0)===1;});
t('Urlaub: entfernt andere Ausrüstung, setzt Basisschilde 0 und startet Dauer 2',()=>{const s=S();s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[0].bezSlots[0].physicalShield=2;s.players[0].bezSlots[0].astralShield=2;s.players[0].hand=[card('Legionsschild').bild];let r=E.equipFromHand(s,0,0,'shield');if(!r.ok)return false;s.players[0].hand=[card('Urlaub').bild];r=E.equipFromHand(s,0,0,'armor');const b=s.players[0].bezSlots[0],a=s.players[0].equipment[0].armor;return r.ok&&b.physicalShield===0&&b.astralShield===0&&!s.players[0].equipment[0].shield&&a.effectRoundsRemaining===2;});
t('Schattenfluchkralle: +1 Berserkermarke nach tatsächlichem Kampf',()=>{const s=S(4);s.players[0].bezSlots[0]=rt('Die ungezähmte Flamme Saphira');s.players[1].bezSlots[0]=rt('Die ungezähmte Flamme Saphira',1);s.players[0].bezSlots[0].ready=true;s.players[1].bezSlots[0].ready=true;s.players[0].bezSlots[0].physicalShield=0;s.players[0].bezSlots[0].astralShield=0;s.players[1].bezSlots[0].physicalShield=0;s.players[1].bezSlots[0].astralShield=0;s.players[0].hand=[card('Schattenfluchkralle').bild];let r=E.equipFromHand(s,0,0,'weapon');if(!r.ok)return false;s.phaseIndex=5;r=E.prepareAttack(s,0,{type:'bez',slot:0},'physical');if(!r.ok)return false;r=E.confirmAttack(s);if(!r.ok)return false;r=E.resolveCombat(s);return r.ok&&Number(s.players[0].bezSlots[0]?.berserkerMarks||0)>=1;});
console.log(`RESULT ${pass} PASS / ${fail} FAIL`);process.exitCode=fail?1:0;
