global.window=global;global.localStorage={getItem:()=>null,setItem(){},removeItem(){}};require('../5goddesses-datenbank.js');require('../game-engine.js');
const E=global.G5Engine,DB=global.GODDESSES_DB.karten;
const card=n=>DB.find(c=>c.name===n||c.name?.includes(n));
let pass=0,fail=0;function t(n,f){try{const r=f();if(r===false)throw Error('false');console.log('PASS',n);pass++;}catch(e){console.error('FAIL',n,'-',e.message);fail++;}}
function rt(n,owner=0,faceDown=false){const c=card(n);if(!c)throw Error('card not found '+n);return {bild:c.bild,owner,stufe:Number(c.stufe||1),hearts:Number(c.herzen||0),physical:Number(c.physische_staerke||0),astral:Number(c.astrale_staerke||0),physicalShield:Number(c.physischer_schild||0),astralShield:Number(c.astraler_schild||0),honor:0,ready:true,faceDown,effectState:{},developmentStack:[c.bild],wonderCostCurrent:Number(c.wunder?.kosten_ehre||0),enteredTurn:0};}
function P(i){return {index:i,name:'P'+(i+1),turnCount:2,honorGrantedTurn:null,hand:[],bezSlots:[null,null],equipment:[{weapon:null,shield:null,armor:null,helmet:null},{weapon:null,shield:null,armor:null,helmet:null}],azr:[null,null,null],primary:null,refuge:rt(DB.find(c=>c.deck_bereich==='zuflucht')?.name||'Zuflucht',i),discard:[],stacks:{bezwingerinnen:[],astral:[],ruestkammer:[]},development:[],recruitedThisTurn:false,drawDone:false};}
function S(){return {version:2,players:[P(0),P(1)],activePlayer:0,startingPlayer:0,phaseIndex:4,sharedSecondary:null,voidZone:[],log:[],attack:null,roundSerial:9,pendingBezEffect:null,pendingDamage:null,pendingWonderDraw:null,pendingEquipment:null,pendingFieldCard:null,winner:null,firstTurn:false};}
function cast(s,n,pi=0,slot=0){s.players[pi].azr[slot]=rt(n,pi,false);return E.startInstantAstralSpell(s,pi,slot);}
function target(s,id){return E.resolveNewAstralSpellTarget(s,id);}
function chooseAllShield(s){let guard=20;while(s.pendingDamage&&guard--){const ch=E.currentShieldChoice(s);if(!ch)break;const src=ch.sources[0];const r=E.chooseShieldSource(s,src.source,src.kind);if(!r.ok)throw Error(r.msg);}if(guard<=0)throw Error('shield loop');}
const astral=DB.filter(c=>String(c.deck_bereich||'').toLowerCase().startsWith('astral')||String(c.kartengruppe||'').toLowerCase().startsWith('astral'));
t('database has exactly 49 Astralkammer cards after duplicate cleanup',()=>astral.length===49);
t('every Astralkammer row has image and name',()=>astral.every(c=>c.name&&c.bild));
t('all 49 Astralkammer cards have an engine effect',()=>astral.every(c=>(c.effekte||[]).some(e=>e&&e.engine_key)));
t('legacy false Vollendete Rettungstechnik duplicate is removed',()=>!card('Vollendete Rettungstechnik'));

// v1.72/v1.74 cards that lacked current regression tests

t('Meteorsturm: even roll can target enemy and deals 1 ASTRAL',()=>{let s=S();s.phaseIndex=4;s.sharedSecondary=rt('Meteorsturm',0);s.sharedSecondary.owner=0;s.sharedSecondary.honor=2;s.players[1].bezSlots[0]=rt('Die verschlingende Flut Calypso',1);let r=E.startMeteorsturmWonder(s,2);if(!r.ok)return false;let ts=E.meteorsturmTargets(s);if(!ts.some(x=>x.id==='1:0'))return false;r=E.resolveMeteorsturmTarget(s,'1:0');chooseAllShield(s);return !s.players[1].bezSlots[0]||s.players[1].bezSlots[0].hearts===1;});
t('Meteorsturm: odd roll permits only own Bezwingerin',()=>{let s=S();s.sharedSecondary=rt('Meteorsturm',0);s.sharedSecondary.owner=0;s.sharedSecondary.honor=2;s.players[0].bezSlots[0]=rt('Die verschlingende Flut Calypso');s.players[1].bezSlots[0]=rt('Die verschlingende Flut Calypso',1);let r=E.startMeteorsturmWonder(s,3);return r.ok&&E.meteorsturmTargets(s).every(x=>x.id.startsWith('0:'));});
t('Feiertag marks enemy for its upcoming turn only',()=>{let s=S();s.players[1].bezSlots[0]=rt('Die verschlingende Flut Calypso',1);let r=cast(s,'Feiertag');if(!r.ok)return false;target(s,'0');return s.players[1].bezSlots[0].effectState.feiertagBlockedTurnCount===s.players[1].turnCount;});
t('Saphiras Upsi deals exactly 1 ASTRAL to open enemy primary',()=>{let s=S();s.players[1].primary=rt('Mornak - Brut',1);s.players[1].primary.hearts=2;let r=cast(s,'Saphiras Upsi');return r.ok&&s.players[1].primary?.hearts===1;});
t('Verwüstung deals 1 physical to secondary without own Wurm',()=>{let s=S();s.sharedSecondary=rt('Dornenwald',1);s.sharedSecondary.owner=1;s.sharedSecondary.hearts=2;let r=cast(s,'Verwüstung');return r.ok&&s.sharedSecondary?.hearts===1;});
t('Verwüstung deals 2 physical with own open Wurm creature',()=>{let s=S();s.sharedSecondary=rt('Dornenwald',1);s.sharedSecondary.owner=1;s.sharedSecondary.hearts=3;s.players[0].primary=rt('Wurzelpeinverschlinger',0);let r=cast(s,'Verwüstung');return r.ok&&s.sharedSecondary?.hearts===1;});
t('Wurzelpeinverschlinger damages occupied secondary on entry',()=>{let s=S();s.sharedSecondary=rt('Dornenwald',1);s.sharedSecondary.owner=1;s.sharedSecondary.hearts=2;const w=rt('Wurzelpeinverschlinger',0);s.players[0].primary=w; // emulate field placement then invoke via public field play instead below unavailable direct
// play from hand to ensure on-play resolves
s.players[0].primary=null;s.players[0].hand=[card('Wurzelpeinverschlinger').bild];let r=E.playFieldFromHand(s,0,'primary');return r.ok&&s.sharedSecondary?.hearts===1;});
t('Wurzelpeinverschlinger locks opponent secondary when empty',()=>{let s=S();s.players[0].hand=[card('Wurzelpeinverschlinger').bild];let r=E.playFieldFromHand(s,0,'primary');return r.ok&&E.secondaryLockedFor(s,1);});
t('Beschützt die Bastion adds one physical refuge shield',()=>{let s=S();s.players[0].refuge.physicalShield=0;let r=cast(s,'Beschützt die Bastion!');return r.ok&&s.players[0].refuge.physicalShield===1;});
t('Bastion-Schutzbarriere adds one ASTRAL refuge shield',()=>{let s=S();s.players[0].refuge.astralShield=0;let r=cast(s,'Bastion-Schutzbarriere');return r.ok&&s.players[0].refuge.astralShield===1;});
t('Auszeichnung can add honor to an open enemy card',()=>{let s=S();s.players[1].bezSlots[0]=rt('Die verschlingende Flut Calypso',1);cast(s,'Auszeichnung');const ts=E.newAstralSpellTargets(s);const id=ts.find(x=>String(x.id).includes('1:bez:0'))?.id||ts.find(x=>x.name?.includes('Calypso'))?.id;if(!id)return false;target(s,id);return s.players[1].bezSlots[0].honor===1;});
t('Demoralisierung permits negative honor',()=>{let s=S();s.players[1].bezSlots[0]=rt('Die verschlingende Flut Calypso',1);s.players[1].bezSlots[0].honor=0;cast(s,'Demoralisierung');target(s,'0');return s.players[1].bezSlots[0].honor===-1;});
t('Neutralisationssiegel destroys a face-down AZR card without activating it',()=>{let s=S();s.players[1].azr[1]=rt('ASTRAL-Feuerball',1,true);cast(s,'Neutralisationssiegel');let ts=E.newAstralSpellTargets(s),id=ts.find(x=>x.id==='1:1')?.id;if(!id)return false;target(s,id);return !s.players[1].azr[1]&&s.players[1].discard.includes(card('ASTRAL-Feuerball').bild);});
t('Legionsrüstung erscheine searches iron armor and equips it',()=>{let s=S();s.players[0].bezSlots[0]=rt('Die verschlingende Flut Calypso');const iron=DB.find(c=>c.kartentyp==='Rüstung'&&String(c.material).toLowerCase()==='eisen');s.players[0].stacks.ruestkammer=[iron.bild];cast(s,'Legionsrüstung erscheine!');let ts=E.newAstralSpellTargets(s);if(!ts.length)return false;target(s,ts[0].id);ts=E.newAstralSpellTargets(s);if(!ts.some(x=>x.id==='0'))return false;target(s,'0');return E.cardData(s.players[0].equipment[0].armor)?.bild===iron.bild;});
t('Dein Angriff scheitert cancels announced enemy attack and blocks attacker this round',()=>{let s=S();s.activePlayer=1;s.phaseIndex=5;s.players[1].bezSlots[0]=rt('Die verschlingende Flut Calypso',1);s.players[0].bezSlots[0]=rt('Die verschlingende Flut Calypso',0);s.attack={attackerKind:'bez',attackerSlot:0,target:{type:'bez',slot:0},attackType:'physical'};let r=cast(s,'Dein Angriff scheitert!',0);return r.ok&&!s.attack&&s.players[1].bezSlots[0].effectState.cannotAttackThisRound===true;});
t('Geheimtechnik Sprint-Angriff removes deployment delay immediately',()=>{let s=S();let b=rt('Die verschlingende Flut Calypso');b.ready=false;s.players[0].bezSlots[0]=b;cast(s,'Geheimtechnik Sprint-Angriff');target(s,'0');return b.ready===true;});
t('Aufstieg develops own Bez for free and preserves damage',()=>{let s=S();let b=rt('Die ungezähmte Flamme Saphira'); // this may match stage2; find stage1 by grund mapping
const d2=DB.find(c=>c.hauptattribut==='BEZWINGERIN'&&Number(c.stufe)===2&&c.name.includes('Saphira'));const d1=DB.find(c=>c.bild===d2.grundkarte_bild);b=rt(d1.name);b.bild=d1.bild;b.stufe=1;b.developmentStack=[d1.bild];b.hearts=Math.max(0,Number(d1.herzen)-1);b.honor=0;s.players[0].bezSlots[0]=b;s.players[0].development=[d2.bild];cast(s,'Aufstieg');target(s,'0');return s.players[0].bezSlots[0].stufe===2&&s.players[0].bezSlots[0].hearts===Math.max(0,Number(d2.herzen)-1)&&s.players[0].bezSlots[0].honor===0;});
t('Exekution destroys any Bez at exactly 1 heart and zero effective shields',()=>{let s=S();let b=rt('Die verschlingende Flut Calypso',1);b.hearts=1;b.physicalShield=0;b.astralShield=0;s.players[1].bezSlots[0]=b;cast(s,'Exekution');let ts=E.newAstralSpellTargets(s);const id=ts.find(x=>x.id==='1:0')?.id;if(!id)return false;target(s,id);return s.players[1].bezSlots[0]===null;});
t('Exekution does not destroy a target that still has shield',()=>{let s=S();let b=rt('Die verschlingende Flut Calypso',1);b.hearts=1;b.physicalShield=1;s.players[1].bezSlots[0]=b;cast(s,'Exekution');let r=target(s,'1:0');return !r.ok&&s.players[1].bezSlots[0]===b&&b.hearts===1;});
t('Zweifache Bestrafung pays 3 honor and arms extra physical fight',()=>{let s=S();let b=rt('Die verschlingende Flut Calypso');b.honor=3;s.players[0].bezSlots[0]=b;cast(s,'Zweifache Bestrafung');target(s,'0');return b.honor===0&&b.effectState.extraPhysicalAttackAvailable===true;});
t('Bis zum bitteren Ende loses 1 heart and grants chosen +1 attack until end round',()=>{let s=S();let b=rt('Die verschlingende Flut Calypso');b.hearts=2;s.players[0].bezSlots[0]=b;cast(s,'Bis zum bitteren Ende');E.resolveBisZumBitterenEndeTarget(s,'0');E.resolveBisZumBitterenEndeChoice(s,'physical');return b.hearts===1&&b.effectState.bitterEndPhysicalBonus===1;});
t('Bis zum bitteren Ende kills a 1-heart target before bonus choice',()=>{let s=S();let b=rt('D.E.A.T.H.');b.hearts=1;s.players[0].bezSlots[0]=b;cast(s,'Bis zum bitteren Ende');let r=E.resolveBisZumBitterenEndeTarget(s,'0');return r.ok&&s.players[0].bezSlots[0]===null&&!s.pendingBezEffect;});
t('Kiki targets only allowed classes and only once per turn',()=>{let s=S();s.phaseIndex=4;s.players[0].primary=rt('Rabe der Hoffnung Kiki');s.players[0].primary.owner=0;s.players[0].primary.effectRoundsRemaining=3;s.players[0].bezSlots[0]=rt('D.E.A.T.H.');s.players[0].bezSlots[1]=rt('Die glorreiche Eroberin Martha Kaizer');let ts=E.kikiEligibleTargets(s);if(!ts.some(x=>x.slot===0)||ts.some(x=>x.slot===1))return false;let r=E.activateKikiDodge(s,0);if(!r.ok)return false;return !E.activateKikiDodge(s,0).ok&&s.players[0].bezSlots[0].effectState.kikiCounterDodgeActive===true;});
t('Lähmende Angst only reacts when own Vengeresse is attack target, then cancels attack',()=>{let s=S();s.activePlayer=1;s.phaseIndex=5;s.players[1].bezSlots[0]=rt('Die verschlingende Flut Calypso',1);s.players[0].bezSlots[0]=rt('Die Bestie Alice Merveilleux',0);s.attack={attackerKind:'bez',attackerSlot:0,target:{type:'bez',slot:0},attackType:'physical'};let r=cast(s,'Lähmende Angst',0);return r.ok&&!s.attack&&s.players[1].bezSlots[0].effectState.cannotAttackThisRound===true;});
t('Vengeresse Vergeltung arms only own Vengeresse and converts physical into ASTRAL for one combat',()=>{let s=S();s.phaseIndex=5;s.players[0].bezSlots[0]=rt('Die Bestie Alice Merveilleux');s.players[0].bezSlots[0].physical=2;s.players[0].bezSlots[0].astral=1;cast(s,'Vengeresse Vergeltung');let ts=E.newAstralSpellTargets(s);if(!ts.some(x=>x.id==='0'))return false;target(s,'0');let st=E.combatStrength(s,0,0,'astral').total;return st>=3&&s.players[0].bezSlots[0].effectState.vengeresseVergeltungActive===true;});
t("Lilou's Gabe permanently adds 1 current heart",()=>{let s=S();let b=rt('Die verschlingende Flut Calypso');b.hearts=1;s.players[0].bezSlots[0]=b;cast(s,"Lilou's Gabe");target(s,'0');return b.hearts===2;});

console.log(`RESULT ${pass} PASS / ${fail} FAIL`);process.exitCode=fail?1:0;
